### ISSUE TITLE
碧海之蓝（25969）下载不了

### ISSUE THREAD

**Issue by Shinaido** [Curange/Bilibili_manga_download#3]
试了几部都正常 [不知道为什么这个就下不动，一直是正在下载第一张然后停住（单话也不行）
![屏幕截图 2021-08-14 082226](https://user-images.githubusercontent.com/42022336/129428799-dfb12841-7a74-48de-9c7c-d159fcee1fff.png)

**Comment by Randark-JMT** [comment]
@ xjbzcvbnm 这个，B站这部漫画的标题里面有中文，导致软件读取的时候会出错
这个问题正在改进中，如有不便之处请多多谅解😂
![图片](https://user-images.githubusercontent.com/56223739/129429707-f41a3d5d-0c16-44b4-95fa-80495715bd73.png)

**Comment by Randark-JMT** [comment]
通过修改部分关键逻辑，已经做到大部分下载功能不受中文影响。
问题代码：ep['short_title'] == str(section)
接下来再找个时间小修一下。。
非常感谢您提出的问题~
